spring.application.name=Trabalho-Estrutura
server.port=8080
spring.config.import=optional:file:./application-local.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/Trabalho-Estrutura
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
